# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  GOOGLE_CLIENT_SECRET: "9_4ngGal1iNs19q2XkfqZPzJ"
  GOOGLE_CLIENT_ID: "616957856379-np632nq7vs49a32pakgppq58m4641gf8.apps.googleusercontent.com"

GMAIL_ADDRESS: "invictus.invoice@gmail.com"
GMAIL_APP_PASSWORD: "aunnyhdezwgxzgyv"

production:
  HOST: "invictuss.herokuapp.com"
